name: CI
on: [push]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run build
        run: |
          yarn --frozen-lockfile
          yarn build:win64
          yarn build-update

